services:
  - type: web
    name: aaft-admissions-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python etl.py"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
